### ISSUE TITLE
What do we do in the case of collisions?

### ISSUE THREAD

**Issue by ghost** [kamalasaurus/twemoji-possum#1]
Some collisions occurred but I'm curious what I'm supposed to do in this situation? Do I add them in manually or?

```
rainbow-flag,1f3f3-fe0f-200d-1f308,1f3f3-fe0f-200d-1f308
japan,1f5fe,1f1ef-1f1f5
turkey,1f983,1f1f9-1f1f7
```

**Comment by kamalasaurus** [comment]
Whoa!  Hello.  I didn't realize this was in use!  So the collision is that there are multiple unicode code-points for those string identifiers?  What is your use-case?  Give me a moment to look through how stuff works -- I haven't looked at this in two years.

**Comment by ghost** [comment]
Oh, it's just an emoji menu. I run `rake` and it finds collisions. Not entirely sure why `rainbow-flag` has a collision when it's two exact same codes. There are two turkeys in the unicode emoji list (one is a bird, the other is a flag) as for Japan, I'm not sure. One is the Japan islands I believe but it's not named the same as "japan" so it's kind of weird.

**Comment by kamalasaurus** [comment]
okay, there is a manual collision management file called `custom-list.csv` in the `tmp` folder.  I *think* that's where you need to make the additions for the collision points.

I think you just need to manually assign a name to the code points.
