### ISSUE TITLE
Remove ⊛ & “ and ” from names

### ISSUE THREAD

**Issue by ghost** [kamalasaurus/twemoji-possum#2]
Removal of ⊛ “ and ” is advised as most users will not be able to type emoji names that contain them and & in the names will break during sass compilation. Adding additional gsub's should suffice.

```ruby
def nameOf node
  name = node.css("td.name")[0]
    .children
    .text
    .downcase
    .strip
    .gsub(/⊛\s/, "")
    .gsub(/&/, "and")
    .gsub(/\s+/, "-")
    .gsub(/,/, "")
    .gsub(/:/, "")
    .gsub("!", "exc")
    .gsub("'", "")
    .gsub(/“|”/, "")
    .gsub("’", "")
    .gsub(/å|ã/, "a")
    .gsub(/é/, "e")
    .gsub(/í/, "i")
    .gsub(/ô/, "o")

  { node: node, name: name }
end
```

**Comment by kamalasaurus** [comment]
can you show me the examples where those actually occur in the designated names?  I haven't kept up with updates in the twemoji ecosystem.

**Comment by ghost** [comment]
In `UnicodeMapper.rb` it retrieves emoji names from https://unicode.org/emoji/charts/full-emoji-list.html and these characters can be found in these names.

The ⊛ icon indicates that the emoji is a new addition. & simply fails during sass compilation. The quotes compile fine they are not your normal " but instead are “ and ” so for most people, typing those emojis would be a little hard.

Examples:
2613 - Wallis & Futuna
2318 - Japanese “here” button
2621 - ⊛ England

**Comment by kamalasaurus** [comment]
```Recently-added emoji are marked by a ⊛ in the name and outlined images;their images may show as a group with “…” before and after.```  oh wow, that's new.  Also, v5.0 -- the unicode consortium has been busy!  It was 3.0 when this was first made.

These rules seem straightforward enough–did you want to make a PR?

**Comment by ghost** [comment]
Not too familiar with pull requests but I think I did it right.

**Comment by kamalasaurus** [comment]
Yep!  So, this issue is now closable!  Not sure what happened to the other issue 🤔
